### ISSUE TITLE
SPLASH 2020 proposal

### ISSUE THREAD

**Issue by rolyp** [live-workshop/proposals#2]
Deadline 1 April, but submit earlier in case they are over-subscribed.
- [x] edit LaTeX sections to match online form – now in .md
- [x] hypothetical PC

**Comment by rolyp** [comment]
Brian notes:

> I’m reviewing the workshop proposal and have a few questions about LIVE’19. Last year the CFP claimed “we would like to reflect on what has been achieved, what has been learnt, and what remains to be done, growing up from a nascent community into a discipline that can build on previous work.” Do you feel there was any progress on that? I’m not sure I feel strongly about having a particular focus other than, as last year, encouraging work to be more reflective about its place in the history of programming environments.
> 
> Similarly, regarding the QA format: did assigning a discussant for each presentation work well? Should we keep it?
>

**Comment by rolyp** [comment]
@brianhempel Added your comments to the relevant GitHub issues. Let’s continue discussion there. Will have some time later to respond.

**Comment by rolyp** [comment]
> I’m reviewing the workshop proposal and have a few questions about LIVE’19. Last year the CFP claimed […] Do you feel there was any progress on that? 

No, and personally I didn't find that part of the CFP compelling. I don't feel "live programming" (whatever that is) is an mature enough topic to get too excited about a retrospective.

> I’m not sure I feel strongly about having a particular focus other than, as last year, encouraging work to be more reflective about its place in the history of programming environments.

Agreed. I don't think we need a specific focus, although we should certainly revamp the CFP to set out the kind of things we might like to see. And the observation about properly contextualising new work remains valid.

> > Similarly, regarding the QA format: did assigning a discussant for each presentation work well? Should we keep it?

We didn’t end up doing that. We could try it this year. I think the most important thing is probably to allow a decent amount of time (10 mins+) for discussion.

**Comment by rolyp** [comment]
@brianhempel Btw, I’m planning to be “business as usual” until there is a compelling reason to do otherwise - regardless of how likely SPLASH is to go ahead. Shall we aim to get a proposal submitted this week? I’m busy until Weds, but then I’ll have some free time to work on it.

**Comment by brianhempel** [comment]
@rolyp Good plan, let's do it. I'll make another pass before Weds.

**Comment by rolyp** [comment]
Great, thanks!

**Comment by brianhempel** [comment]
I removed the blurb about a focus on retrospective and replaced it with this instead, with appropriate re-adaptation throughout the proposal:

> The study of live programming is now a [re-]established area of research. The LIVE workshop emphasizes the human experience of programming with an interest in reconsidering traditional practices and beliefs. LIVE is a forum for early-stage work to receive constructive criticism. We accept short papers, web essays with embedded videos, and demo videos. Traditionally, the majority of LI VE submissions are demonstrations of novel programming systems—we encourage such demos to include a reflection about their place in the history of programming environments. LIVE additionally accepts and welcomes experience reports, literature reviews, and position papers.

**Comment by rolyp** [comment]
Thanks Brian. I’ve made a few minor changes so far, but nothing major. I feel the CFP needs a reboot but let’s aim to do that after 1 April.

It seems the workshop proposal is now submitted via an [online form](https://2020.splashcon.org/createProposal/d3e6571b-e02a-4eb5-82d3-1cf699e69fba) rather than PDF. (If it was like that last year, I’ve forgotten.) Let’s edit the sections of the PDF so that they match the online form; then we can just cut-and-paste once we’re done. For example, we can merge “Abstract” with “Theme, Goals and Format” into a single “Description” section. 

For the PC, perhaps we should come up with a small list (say 10) of people it would be nice to have in an ideal world (i.e. nicely balanced, good gender mix).

**Comment by brianhempel** [comment]
I made a Markdown file that matches the form. Markdown is a bit less clunky than TeX, I can use a WYSIWYG editor ([Typora](https://typora.io/)), and the form fields are Markdown anyway.

I've migrated the appropriate sections from the TeX to the Markdown, so the Markdown is canonical now. There's a few numbers to fill in and the PC list is bare for now. Tomorrow I'll think about some possible PC members. I added an OASIcs blurb to the CFP. The only bits of the TeX doc that didn't make it into the Markdown are the sentence about inviting "keynote talks that span these fields", the sentence about having a reflecting session at LIVE, and the bit about intensity from standing room only.

**Comment by rolyp** [comment]
Good idea. I’ll think about PC members as well. While the list remains small it would be good to aim for as close to a 50-50 gender split as we can get, because that ratio will probably get smaller as the PC gets bigger..

**Comment by rolyp** [comment]
I’ve added someone to the PC (Juliana Franco; she agreed last year, but her email address went stale after graduating and unfortunately she missed out on all the correspondence). I think this will probably do for now, we can review the current list and add potential new people if/when the proposal is accepted.

I’ve made a couple of other minor tweaks, including dropping the bit that probably crept in last year about “practices and beliefs” (makes it sound like a yoga class. I’m happy to submit; if you are as well, feel free to go ahead and submit. (Or least it to me if you prefer.)

**Comment by brianhempel** [comment]
I submitted! I wrote that we expected 45 people, range 25-70. And I imagine you received a 'SPLASH Workshops - Conference/Workshop proposal "LIVE 2020" submitted' confirmation email, since I listed you as a submitter.

**Comment by rolyp** [comment]
Cool, thanks! I guess we should assume we’re going ahead (if proposal accepted) – if not in person then [online](https://www.acm.org/virtual-conferences).
